### ISSUE TITLE
link ~/.local/share/ska/dockerfile/values.toml .temp-values.toml: no such file or directory

### ISSUE THREAD

**Issue by sebastianmacias** [xdefrag/ska#16]
Hi there,

After installing ska, I copied the contents of https://github.com/xdefrag/ska/tree/master/examples/dockerfile to ~/.local/share/ska/dockerfile

and then on a terminal I ran: 
```bash
$ ska dockerfile
```

and got the following error msg: 

```bash
link ~/.local/share/ska/dockerfile/values.toml .temp-values.toml: no such file or directory
```

**Comment by xdefrag** [comment]
@sebastianmacias Greetings. Thanks for pointing it out, it's a bug. Fixed it with https://github.com/xdefrag/ska/commit/7a73430c7190cc485e7c93573bf28df85f813f06

For now project in early stages, I use it at work a lot, but with this commit https://github.com/xdefrag/ska/commit/f3d5bdbd03b6cf19b51ebaa6d06b99021bf55452. It may be suggested as somewhat stable.

Master branch is my struggle to allocate some time and create first real stable release.

**Comment by sebastianmacias** [comment]
@xdefrag excellent. I will test it and let you know if I run into anything.
