### ISSUE TITLE
Add error types with helpful messages

### ISSUE THREAD

**Issue by ysamlan** [xdefrag/ska#28]
A colleague ran into this because she didn't have $EDITOR set:

```bash
unset EDITOR
```
Then when running ska against a template:
```
main.go:41: fork/exec : no such file or directory
```

Would be good to either default or at least print a useful error if $EDITOR isn't set.

**Comment by ysamlan** [comment]
Additionally, after setting $EDITOR again in this scenario this happens:

```main.go:59: link /Users/yoni/projects/go-skeletons/go-service/values.toml /var/folders/z9/z615fz356z56x4z54ttw0dk40000gn/T//temp-values.toml: file exists``` 

Which I think is because the no-$EDITOR run didn't clean up after itself?

**Comment by xdefrag** [comment]
@ysamlan Yeah, in ska there is no error preparations right now. If there is any fatal error app just prints it to stderr:

```go
func must(err error) {
	if err != nil {
		_, file, line, _ := runtime.Caller(1)
		fmt.Fprintf(os.Stderr, "%s:%d: %v\n", filepath.Base(file), line, err)
		os.Exit(-1)
	}
}
```

I added this issue to the next project milestone.
