### ISSUE TITLE
Is there anyway to get current template name (as dest dir name or path)?

### ISSUE THREAD

**Issue by leopku** [xdefrag/ska#29]
I wanna generate file like this:

```go
package main

import (
  "github.com/leopku/mydest/pkg"
)
```
How can I get variable `mydest` while running with `ska mydest`?

**Comment by leopku** [comment]
A simple implement is here https://github.com/leopku/ska/blob/db267110eec84c522ab82504db0a52d346f0c3ea/main.go#L62

And test case - which reusing filenames template is here https://github.com/leopku/ska/blob/db267110eec84c522ab82504db0a52d346f0c3ea/examples/filenames/templates/%7B%7B.svc%7D%7D/%7B%7B.svc%7D%7D.txt#L3

If needed, I can make a PR.

**Comment by xdefrag** [comment]
@leopku In my opinion static values must be static and variables should be variables. If you want to change it later, use values.toml and templates, in any other way just use static text.

**Comment by leopku** [comment]
@xdefrag got it.

Thanks.
